pipeline {
    agent {
        node {
            label 'master'
        }
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    
    stages {
        stage('Validate') {
            steps {
                dir('packer') {
                    powershell "packer validate packer.json"
                }
            }
        }
        
        stage('Bake AMI') {
            steps {
                dir('packer') {
                    powershell "packer build packer.json"
                }
            }
        }
    }
}